import type { ExerciseTemplate } from './exercise-db';

/**
 * MOVEMENTS THE CHANNEL HAS FILMED THAT THE APP DID NOT HAVE.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THIS FILE EXISTS
 * ─────────────────────────────────────────────────────────────────────────────
 * Demo videos are recorded on @GrowPerformanceRehabilitation and matched to
 * exercises in lib/exercise-videos.ts. Cross-referencing the channel against the
 * catalogue turned up thirty movements that had been filmed and had nowhere to
 * go — trap bar work, gorilla rows, banded monster walks, and a plain front
 * plank, which the app somehow lacked while carrying a side plank and a weighted
 * plank.
 *
 * A video with no exercise behind it is a recording nobody will ever see. So
 * rather than leaving them stranded, each one is a real exercise here: fully
 * classified, tiered, and spliced into the pool it belongs to.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THEY ARE HERE AND NOT IN exercise-db.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * They ARE in exercise-db.ts, as far as the rest of the app is concerned — the
 * splice at the bottom of that file pushes each one into its collection before
 * anything reads them, so they are generated into sessions, pickable in the
 * custom builder and counted in the catalogue like any other movement.
 *
 * Keeping the SOURCE here is about review. exercise-db.ts is twenty thousand
 * lines; thirty new entries scattered through it by session type and equipment
 * tier would be unreviewable, and this is content a coach needs to be able to
 * check. One file, one purpose, one place to look when the next batch of videos
 * goes up.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE TIER RULE, WHICH IS THE ONE THAT MATTERS
 * ─────────────────────────────────────────────────────────────────────────────
 * `tier` is not a label, it is a promise. Onboarding asks the user what they own
 * and the first option is "No Equipment". An exercise filed below the kit it
 * actually needs gets handed to someone who cannot do it, in a slot the session
 * will not let them skip.
 *
 *   bodyweight : nothing, or resistance bands
 *   dumbbells  : dumbbells and kettlebells
 *   fullgym    : barbells, trap bars, cables, machines, boxes, sleds, med balls
 *
 * It is checked against the exercise's own WORDS, not just its declaration —
 * see tests/equipment-honesty.check.mjs, which exists because a Chin-Up once
 * declared "bodyweight" and a beginner with no pull-up bar was told to do five.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ADDING MORE
 * ─────────────────────────────────────────────────────────────────────────────
 * See CHANNEL-REFRESH.md. In short: refresh the channel snapshot, run
 * `npm run video-status`, and read the "Uploads not yet used by the app"
 * section — anything filmed with no home lands there.
 */
export interface ChannelExercise {
  /** Which pool it joins. Mirrors the collections in lib/exercise-db.ts. */
  collection: 'ACCESSORIES' | 'NEURO' | 'PREP' | 'PREHAB' | 'FINISHERS';
  /** squat = squat pattern, deadlift = hinge and back, bench = upper-body push. */
  sessionType: 'squat' | 'bench' | 'deadlift';
  tier: 'bodyweight' | 'dumbbells' | 'fullgym';
  template: ExerciseTemplate;
}


export const CHANNEL_EXERCISES: ChannelExercise[] = [
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Trapbar Deadlift".
    template: {
      id: 'ch-trap-bar-deadlift',
      name: 'Trap Bar Deadlift',
      sets: 4,
      reps: '6-8 reps',
      cue: 'Stand inside the frame, grip the neutral handles, chest tall and push the floor away - the more upright torso takes load off the lower back',
      suggestedLoad: '60-100 kg',
      category: 'accessory',
      targetRegions: ['hamstrings', 'glutes', 'quads', 'lower_back', 'hip_groin'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Glutes',
      secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Erector spinae', 'Trapezius', 'Core'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Rack Pull',
        cue: 'Bar set just below the knees, drive the hips through and squeeze glutes at the top - shorter range, same posterior chain',
        suggestedLoad: '60-100 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Trapbar Romanian Deadlift".
    template: {
      id: 'ch-trap-bar-romanian-deadlift',
      name: 'Trap Bar Romanian Deadlift',
      sets: 3,
      reps: '8-10 reps',
      cue: 'Start tall inside the frame, push the hips back with soft knees until the hamstrings stretch, then drive the hips forward - handles stay close to the legs',
      suggestedLoad: '50-80 kg',
      category: 'accessory',
      targetRegions: ['hamstrings', 'glutes', 'lower_back', 'hip_groin'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Hamstrings',
      secondaryMuscles: ['Glutes', 'Erector spinae', 'Core'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Barbell Romanian Deadlift',
        cue: 'Straight bar in front of the thighs, same hip push and hamstring stretch - the load sits in front rather than at your sides',
        suggestedLoad: '50-80 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Trapbar Rows".
    template: {
      id: 'ch-trap-bar-row',
      name: 'Trap Bar Row',
      sets: 3,
      reps: '10-12',
      cue: 'Hinge over inside the frame with a flat back, pull the handles to your ribs and squeeze the shoulder blades - lower under control',
      suggestedLoad: '40-70 kg',
      category: 'accessory',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rhomboids', 'Biceps', 'Rear deltoid', 'Erector spinae'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Pendlay Row',
        cue: 'Barbell from a dead stop on the floor each rep, explosive pull to the ribs - same mid-back work with a straight bar',
        suggestedLoad: '40-60 kg',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Trapbar Jumps".
    template: {
      id: 'ch-trap-bar-jump',
      name: 'Trap Bar Jump',
      sets: 3,
      reps: '4 explosive',
      cue: 'Set up as for a trap bar deadlift with a light load, stand up as fast as you can and jump off the floor - land soft with bent knees and reset every rep',
      suggestedLoad: '40-60 kg',
      category: 'neuro',
      targetRegions: ['glutes', 'quads', 'hamstrings', 'hip_groin', 'knee', 'calf_shin'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Glutes',
      secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
      equipmentRequired: 'barbell',
      difficulty: 'advanced',
      isUnilateral: false,
      swapAlternative: {
        name: 'Hang Pull',
        cue: 'Barbell at the hips, short hinge then explosive extension and shrug to chest height - same triple extension with no landing impact',
        suggestedLoad: '50-70 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'fullgym',
    // Demonstrated by the channel video "Box Squat".
    template: {
      id: 'ch-box-squat',
      name: 'Box Squat',
      sets: 4,
      reps: '5-6 reps',
      cue: 'Sit back onto the box under control, pause with the weight still in your feet, then drive up hard - the box sets your depth, never relax onto it',
      suggestedLoad: '50-80 kg',
      category: 'accessory',
      targetRegions: ['quads', 'hamstrings', 'glutes', 'knee', 'hip_groin', 'lower_back'],
      videoId: '',
      movementPattern: 'squat',
      primaryMuscle: 'Quadriceps',
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Erector spinae', 'Core'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Pause Squat',
        cue: 'Same bar and stance, hold two seconds at the bottom instead of sitting onto a box - same control demand without needing a box',
        suggestedLoad: '50-75 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Standing Dumbbell Rows".
    template: {
      id: 'ch-standing-dumbbell-row',
      name: 'Standing Dumbbell Row',
      sets: 3,
      reps: '10-12',
      cue: 'Hinge forward to about 45 degrees with a flat back, pull both dumbbells up to your hips and squeeze the shoulder blades together - lower slowly and keep the torso still',
      suggestedLoad: '14-24 kg per hand',
      category: 'accessory',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder', 'bicep', 'lower_back'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rhomboids', 'Trapezius', 'Biceps', 'Rear deltoid', 'Erector spinae'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'DB Chest-Supported Row',
        cue: 'Chest on an incline bench, pull both dumbbells to your hips - same back muscles with the lower back taken out of it',
        suggestedLoad: '12-20 kg per hand',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Gorilla Rows".
    template: {
      id: 'ch-gorilla-row',
      name: 'Gorilla Row',
      sets: 3,
      reps: '10 each side',
      cue: 'Two dumbbells or kettlebells on the floor between your feet, hinge over with a flat back, and row one to your hip while the other stays resting on the floor - keep the hips square and alternate sides',
      suggestedLoad: '16-28 kg per hand',
      category: 'accessory',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder', 'core_ribs', 'lower_back'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rhomboids', 'Biceps', 'Core', 'Erector spinae', 'Trapezius'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Single-Arm Row',
        cue: 'One hand braced on a bench, row the other dumbbell to your hip - same lat work with the back fully supported',
        suggestedLoad: '16-26 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Alternating Dumbbell Curls".
    template: {
      id: 'ch-alternating-dumbbell-curl',
      name: 'Alternating Dumbbell Curl',
      sets: 3,
      reps: '10 each side',
      cue: 'Elbows pinned to your sides, curl one dumbbell at a time and turn the palm up as it rises - lower it over two seconds before the other arm starts',
      suggestedLoad: '8-16 kg per hand',
      category: 'accessory',
      targetRegions: ['bicep', 'elbow'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Biceps',
      secondaryMuscles: ['Brachialis', 'Brachioradialis'],
      equipmentRequired: 'dumbbells',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Hammer Curl',
        cue: 'Neutral grip, thumbs up throughout - same elbow flexion with more brachialis and forearm',
        suggestedLoad: '8-16 kg per hand',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Single Arm Dumbbell Press".
    template: {
      id: 'ch-single-arm-dumbbell-overhead-pre',
      name: 'Single-Arm Dumbbell Overhead Press',
      sets: 3,
      reps: '8-10 each side',
      cue: 'Stand tall with one dumbbell at your shoulder, brace your core hard and press straight overhead without leaning away from it - lower under control',
      suggestedLoad: '10-20 kg',
      category: 'accessory',
      targetRegions: ['front_shoulder', 'core_ribs', 'tricep', 'upper_back'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Anterior deltoid',
      secondaryMuscles: ['Triceps', 'Core', 'Trapezius'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Half-Kneeling DB Press',
        cue: 'Same one-arm press from a half-kneeling stance - takes the lower back out of it and stops you leaning',
        suggestedLoad: '8-16 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Alternating Dumbbell Press".
    template: {
      id: 'ch-alternating-dumbbell-overhead-pr',
      name: 'Alternating Dumbbell Overhead Press',
      sets: 3,
      reps: '8 each side',
      cue: 'Both dumbbells at your shoulders, press one straight overhead while the other stays at your shoulder, then swap - keep the ribs down and do not lean side to side',
      suggestedLoad: '10-18 kg per hand',
      category: 'accessory',
      targetRegions: ['front_shoulder', 'core_ribs', 'tricep'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Anterior deltoid',
      secondaryMuscles: ['Triceps', 'Core', 'Lateral deltoid'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Standing Overhead Press',
        cue: 'Press both dumbbells overhead together - same deltoid load with a shorter set and less balance demand',
        suggestedLoad: '10-18 kg per hand',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Alternating Dumbbell Bench Press".
    template: {
      id: 'ch-alternating-dumbbell-bench-press',
      name: 'Alternating Dumbbell Bench Press',
      sets: 3,
      reps: '8 each side',
      cue: 'Lie back with both dumbbells locked out over your chest, lower one to chest level and press it back up while the other arm holds still at the top - alternate sides each rep',
      suggestedLoad: '14-24 kg per hand',
      category: 'accessory',
      targetRegions: ['chest', 'tricep', 'front_shoulder', 'core_ribs'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Pectorals',
      secondaryMuscles: ['Triceps', 'Anterior deltoid', 'Core'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Dumbbell Bench Press',
        cue: 'Press both dumbbells together - same chest and triceps work without the long hold on the resting arm',
        suggestedLoad: '16-28 kg per hand',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Bench Dumbbell Reverse Fly".
    template: {
      id: 'ch-bench-dumbbell-reverse-fly',
      name: 'Bench Dumbbell Reverse Fly',
      sets: 3,
      reps: '12-15',
      cue: 'Lie chest-down on an incline bench with the dumbbells hanging straight below you, sweep them out wide to shoulder height with soft elbows and squeeze the shoulder blades - lower slowly and keep the neck relaxed',
      suggestedLoad: '5-10 kg per hand',
      category: 'accessory',
      targetRegions: ['rear_shoulder', 'upper_back'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Rear deltoid',
      secondaryMuscles: ['Rhomboids', 'Trapezius'],
      equipmentRequired: 'dumbbells',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'DB Bent-Over Lateral Raise',
        cue: 'Same wide sweep hinged over on your feet - no bench needed, but the lower back has to hold the position',
        suggestedLoad: '4-8 kg per hand',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Kettlebell Side Lunge".
    template: {
      id: 'ch-kb-side-lunge',
      name: 'KB Side Lunge',
      sets: 3,
      reps: '12 each side',
      cue: 'Hold the bell at your chest, step wide to one side and sit into that hip while the other leg stays straight - push back through the heel to stand',
      suggestedLoad: '12-20 kg',
      category: 'accessory',
      targetRegions: ['hip_groin', 'quads', 'glutes', 'hamstrings', 'knee'],
      videoId: '',
      movementPattern: 'lunge',
      primaryMuscle: 'Adductors',
      secondaryMuscles: ['Glutes', 'Quadriceps', 'Hamstrings'],
      equipmentRequired: 'kettlebell',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Cossack Squat',
        cue: 'Same wide stance with no weight, sit deep into one hip with the other leg straight and heel down',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Kettlebell Romanian Deadlifts".
    template: {
      id: 'ch-kb-romanian-deadlift',
      name: 'KB Romanian Deadlift',
      sets: 3,
      reps: '12-15',
      cue: 'Soft knees, push the hips back and let the bell slide down the thighs until the hamstrings pull tight - stand tall and squeeze the glutes',
      suggestedLoad: '16-28 kg',
      category: 'accessory',
      targetRegions: ['hamstrings', 'glutes', 'lower_back'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Hamstrings',
      secondaryMuscles: ['Glutes', 'Erector spinae', 'Core'],
      equipmentRequired: 'kettlebell',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Single-Leg KB Romanian Deadlift',
        cue: 'One bell, hinge over one leg and reach it toward the floor - same hamstring stretch with a balance demand',
        suggestedLoad: '12-20 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Split Stance Romanian Deadlifts".
    template: {
      id: 'ch-db-split-stance-romanian-deadlif',
      name: 'DB Split-Stance Romanian Deadlift',
      sets: 3,
      reps: '10 each side',
      cue: 'Stagger the feet so the back toe only rests for balance, hinge over the front leg and slide the dumbbells down that thigh - drive the front hip forward to stand',
      suggestedLoad: '10-18 kg per hand',
      category: 'accessory',
      targetRegions: ['hamstrings', 'glutes', 'hip_groin', 'lower_back'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Hamstrings',
      secondaryMuscles: ['Glutes', 'Erector spinae', 'Core'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Single-Leg RDL',
        cue: 'Back foot off the floor entirely, hinge and reach toward the ground - same hamstring loading with more balance demand',
        suggestedLoad: '8-16 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Seated Wide Grip Rows".
    template: {
      id: 'ch-seated-wide-grip-cable-row',
      name: 'Seated Wide-Grip Cable Row',
      sets: 3,
      reps: '12-15',
      cue: 'Wide grip on the bar, sit tall and pull high to the sternum with the elbows flaring out to the sides - lats and rear delts rather than a shrug, then control the return',
      suggestedLoad: '35-55 kg',
      category: 'accessory',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rear deltoid', 'Rhomboids', 'Biceps'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'DB Chest-Supported Row',
        cue: 'Chest on an incline bench, elbows wide, pull towards the ribs - same wide-elbow back work without a cable stack',
        suggestedLoad: '12-18 kg per hand',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Seated Single Arm Rows".
    template: {
      id: 'ch-seated-single-arm-cable-row',
      name: 'Seated Single-Arm Cable Row',
      sets: 3,
      reps: '12 each side',
      cue: 'One handle at a time, let the shoulder blade reach forward at the start then pull the handle back to your hip and squeeze - keep the torso square instead of twisting with it',
      suggestedLoad: '20-35 kg',
      category: 'accessory',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder', 'core_ribs'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rhomboids', 'Biceps', 'Rear deltoid', 'Core'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Single-Arm Row',
        cue: 'Knee and hand on a bench, pull the dumbbell to your hip and lower it slowly - same one-sided lat work with a dumbbell',
        suggestedLoad: '14-22 kg',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Skater Jumps".
    template: {
      id: 'ch-skater-jump',
      name: 'Skater Jump',
      sets: 3,
      reps: '6 each side',
      cue: 'Push off the outside foot and bound sideways onto the other leg, swinging the arms across the body - stick the landing on one foot and hold it steady before bounding back',
      suggestedLoad: 'Bodyweight',
      category: 'neuro',
      targetRegions: ['glutes', 'hip_groin', 'knee', 'quads', 'ankle_achilles'],
      videoId: '',
      movementPattern: 'squat',
      primaryMuscle: 'Glutes',
      secondaryMuscles: ['Glute medius', 'Quadriceps', 'Calves'],
      equipmentRequired: 'bodyweight',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Lateral Jump',
        cue: 'Push off the outside foot and jump sideways, landing on two feet - same sideways power with a simpler landing',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Split Squat Jumps".
    template: {
      id: 'ch-split-squat-jump',
      name: 'Split Squat Jump',
      sets: 3,
      reps: '5 each side',
      cue: 'Drop into a split stance with the back knee low, then jump straight up off both feet and land back in the same stance - land soft and reset the position before the next rep',
      suggestedLoad: 'Bodyweight',
      category: 'neuro',
      targetRegions: ['quads', 'glutes', 'hip_groin', 'knee'],
      videoId: '',
      movementPattern: 'lunge',
      primaryMuscle: 'Quadriceps',
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'],
      equipmentRequired: 'bodyweight',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Jump Lunge',
        cue: 'Same jump but switch the feet in the air and land in the opposite split stance - alternate every rep',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'squat',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Dumbbell Split Squat Jumps".
    template: {
      id: 'ch-db-split-squat-jump',
      name: 'DB Split Squat Jump',
      sets: 3,
      reps: '5 each side',
      cue: 'Light dumbbells hanging at your sides, drop into the split stance and jump straight up - land soft in the same stance and keep the weight light so the speed stays high',
      suggestedLoad: '5-10 kg per hand',
      category: 'neuro',
      targetRegions: ['quads', 'glutes', 'hip_groin', 'knee'],
      videoId: '',
      movementPattern: 'lunge',
      primaryMuscle: 'Quadriceps',
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'],
      equipmentRequired: 'dumbbells',
      difficulty: 'advanced',
      isUnilateral: true,
      swapAlternative: {
        name: 'Split Squat Jump',
        cue: 'Same jump with nothing in the hands - drop the load and keep the intent',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'squat',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Dumbbell Squat Jumps".
    template: {
      id: 'ch-db-squat-jump',
      name: 'DB Squat Jump',
      sets: 3,
      reps: '5 explosive',
      cue: 'Dumbbells hanging at your sides, dip to about half depth and jump as high as you can - land soft with bent knees and reset between every rep',
      suggestedLoad: '6-12 kg per hand',
      category: 'neuro',
      targetRegions: ['quads', 'glutes', 'knee', 'hip_groin', 'calf_shin'],
      videoId: '',
      movementPattern: 'squat',
      primaryMuscle: 'Glutes',
      secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
      equipmentRequired: 'dumbbells',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Squat Jump',
        cue: 'Same jump with no dumbbells - full depth, maximum height, land soft',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'squat',
    tier: 'fullgym',
    // Demonstrated by the channel video "Seated Box Jumps".
    template: {
      id: 'ch-seated-box-jump',
      name: 'Seated Box Jump',
      sets: 3,
      reps: '5 jumps',
      cue: 'Sit tall on a low box with both feet planted, then jump up onto the box in front of you without dipping down first - step off, sit back down and reset every rep',
      suggestedLoad: 'Bodyweight',
      category: 'neuro',
      targetRegions: ['quads', 'glutes', 'knee', 'hip_groin'],
      videoId: '',
      movementPattern: 'squat',
      primaryMuscle: 'Glutes',
      secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
      equipmentRequired: 'full gym',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Box Jump (Step-Down)',
        cue: 'Jump onto the box from standing and step down - same target with a normal dip and arm swing',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'bench',
    tier: 'fullgym',
    // Demonstrated by the channel video "Medball Floor Chest Pass".
    template: {
      id: 'ch-med-ball-floor-chest-pass',
      name: 'Med Ball Floor Chest Pass',
      sets: 3,
      reps: '6 explosive',
      cue: 'Ball held at chest height, drive it away from you and down into the floor a few metres ahead with both arms - collect it, reset your stance and throw with full intent each rep',
      suggestedLoad: '4-6 kg ball',
      category: 'neuro',
      targetRegions: ['chest', 'front_shoulder', 'core_ribs'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Pectorals',
      secondaryMuscles: ['Triceps', 'Anterior deltoid', 'Core'],
      equipmentRequired: 'full gym',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Med Ball Chest Pass (Wall)',
        cue: 'Same chest pass into a wall so the ball comes straight back - catch and reload without walking after it',
        suggestedLoad: '4-6 kg ball',
      },
    },
  },
  {
    collection: 'NEURO',
    sessionType: 'bench',
    tier: 'fullgym',
    // Demonstrated by the channel video "Supine Medball Throws".
    template: {
      id: 'ch-supine-med-ball-throw',
      name: 'Supine Med Ball Throw',
      sets: 3,
      reps: '6 explosive',
      cue: 'Lie on your back with the ball on your chest and punch it straight up as fast as you can, catching it as it drops - keep it travelling over your chest, not your face',
      suggestedLoad: '3-5 kg ball',
      category: 'neuro',
      targetRegions: ['chest', 'front_shoulder', 'elbow'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Pectorals',
      secondaryMuscles: ['Triceps', 'Anterior deltoid'],
      equipmentRequired: 'full gym',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Med Ball Chest Pass (Wall)',
        cue: 'Standing chest pass into a wall - same press throw with nothing coming back down over you',
        suggestedLoad: '4-6 kg ball',
      },
    },
  },
  {
    collection: 'FINISHERS',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Sled Rows".
    template: {
      id: 'ch-sled-row',
      name: 'Sled Row',
      sets: 4,
      reps: '15 m each round',
      cue: 'Face the sled with a handle in each hand, hinge slightly and row both handles to your ribs, then step back and pull again - chest tall, squeeze the shoulder blades on every pull',
      suggestedLoad: '30-50 kg sled',
      category: 'finisher',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder', 'bicep'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rhomboids', 'Rear deltoid', 'Biceps', 'Core'],
      equipmentRequired: 'full gym',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'Seated Cable Row',
        cue: 'Upright torso, pull the handle to the navel and squeeze the shoulder blades - slow return',
        suggestedLoad: '30-50 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Plank".
    template: {
      id: 'ch-plank',
      name: 'Plank',
      sets: 3,
      reps: '30-60s',
      cue: 'Forearms under the shoulders, body in one straight line from head to heels - squeeze the glutes, brace the stomach and keep breathing instead of holding your breath',
      suggestedLoad: 'Bodyweight',
      category: 'accessory',
      targetRegions: ['core_ribs', 'lower_back'],
      videoId: '',
      movementPattern: 'isometric',
      primaryMuscle: 'Transversus abdominis',
      secondaryMuscles: ['Obliques', 'Glutes', 'Erector spinae'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Dead Bug',
        cue: 'On your back, lower one arm and the opposite leg while the lower back stays pressed to the floor - same anti-extension core work lying down',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREHAB',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Banded Monster Walks".
    template: {
      id: 'ch-banded-monster-walk',
      name: 'Banded Monster Walk',
      sets: 2,
      reps: '10 steps forward and 10 back',
      cue: 'Band around the ankles, drop into a quarter squat and step diagonally forward then diagonally back, keeping the feet wider than the hips and the toes pointing ahead the whole time',
      suggestedLoad: 'Light band',
      category: 'prehab',
      targetRegions: ['glutes', 'hip_groin', 'knee'],
      videoId: '',
      movementPattern: 'rehabilitation',
      primaryMuscle: 'Glute medius',
      secondaryMuscles: ['Glutes', 'Hip external rotators', 'Quadriceps'],
      equipmentRequired: 'resistance bands',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Banded Lateral Walk',
        cue: 'Same band and same low stance, stepping sideways instead of diagonally - keeps constant tension on the outer hip',
        suggestedLoad: 'Light band',
      },
    },
  },
  {
    collection: 'PREHAB',
    sessionType: 'deadlift',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Banded Marches".
    template: {
      id: 'ch-banded-march',
      name: 'Banded March',
      sets: 2,
      reps: '10 each side',
      cue: 'Loop a band around both feet, stand tall and drive one knee up to hip height against the band - hold a second, lower under control and do not let the standing hip drop or the torso lean back',
      suggestedLoad: 'Light band',
      category: 'prehab',
      targetRegions: ['hip_groin', 'core_ribs', 'lower_back'],
      videoId: '',
      movementPattern: 'rehabilitation',
      primaryMuscle: 'Hip flexors',
      secondaryMuscles: ['Core', 'Glutes', 'Glute medius'],
      equipmentRequired: 'resistance bands',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'Glute Bridge March',
        cue: 'On your back with the hips up, lift each foot in turn without letting the hips tip - the same stability demand from the floor',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREP',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Kneeling Rocks".
    template: {
      id: 'ch-kneeling-rock-back',
      name: 'Kneeling Rock-Back',
      sets: 1,
      reps: '10 slow reps',
      cue: 'On all fours with hands under the shoulders and knees under the hips, set a flat back and rock the hips towards the heels as far as they go before the lower back rounds - then rock forward to the start',
      suggestedLoad: 'Bodyweight',
      category: 'prep',
      targetRegions: ['hip_groin', 'lower_back', 'knee'],
      videoId: '',
      movementPattern: 'mobility',
      primaryMuscle: 'Glutes',
      secondaryMuscles: ['Adductors', 'Erector spinae'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Child\'s Pose',
        cue: 'Sit the hips back onto the heels and reach the arms long - the same hip and lower back opener held still instead of rocking',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREHAB',
    sessionType: 'bench',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Seated Shoulder External Rotations".
    template: {
      id: 'ch-seated-shoulder-external-rotatio',
      name: 'Seated Shoulder External Rotation (Band)',
      sets: 2,
      reps: '12 each side',
      cue: 'Sit tall holding a band between both hands with the elbows pinned to your ribs at 90°, rotate the forearms outward against the band, pause, then return slowly without shrugging or letting the elbows drift',
      suggestedLoad: 'Light band',
      category: 'prehab',
      targetRegions: ['rear_shoulder', 'front_shoulder', 'upper_back'],
      videoId: '',
      movementPattern: 'rotation',
      primaryMuscle: 'Infraspinatus',
      secondaryMuscles: ['Teres minor', 'Rear deltoid'],
      equipmentRequired: 'resistance bands',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Prone Shoulder External Rotation',
        cue: 'Face down on a bed or bench, elbow at 90°, rotate the hand up towards shoulder height - the same rotator cuff work with no band at all',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  // ───────────────────────────────────────────────────────────────────────────
  // SECOND BATCH — the 24 uploads added after 13 August 2026.
  //
  // Seven of them matched an exercise the app already had and are simply mapped
  // in lib/exercise-videos.ts. One is a second take of a movement already
  // covered. The sixteen below had nowhere to go: the cable station was almost
  // untouched by the catalogue, the landmine had one press and nothing else, and
  // the calf work stopped at a straight-knee raise with no soleus variant and
  // nothing at all for the shin.
  // ───────────────────────────────────────────────────────────────────────────
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'fullgym',
    // Demonstrated by the channel video "Cable Lateral Raises".
    template: {
      id: 'ch-cable-lateral-raise',
      name: 'Cable Lateral Raise',
      sets: 3,
      reps: '12-15',
      cue: 'Low cable behind you, handle in the far hand, lead with the elbow out to shoulder height - the cable keeps tension at the bottom where a dumbbell has none',
      suggestedLoad: '5-15 kg',
      category: 'accessory',
      targetRegions: ['front_shoulder', 'rear_shoulder', 'upper_back'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Lateral deltoid',
      secondaryMuscles: ['Anterior deltoid', 'Trapezius'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Lateral Raise',
        cue: 'Same path with a dumbbell, lead with the elbow and stop at shoulder height - lower over two seconds',
        suggestedLoad: '5-12 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Seated Lateral Raises".
    template: {
      id: 'ch-seated-lateral-raise',
      name: 'Seated DB Lateral Raise',
      sets: 3,
      reps: '12-15',
      cue: 'Sat upright on the end of a bench, raise both dumbbells out to shoulder height with a soft elbow - sitting down stops the legs helping, so the shoulder does all of it',
      suggestedLoad: '4-10 kg',
      category: 'accessory',
      targetRegions: ['front_shoulder', 'rear_shoulder', 'upper_back'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Lateral deltoid',
      secondaryMuscles: ['Anterior deltoid', 'Trapezius'],
      equipmentRequired: 'dumbbells',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'DB Lateral Raise',
        cue: 'Standing version of the same raise - keep the torso still rather than swinging the weight up',
        suggestedLoad: '5-12 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'bench',
    tier: 'fullgym',
    // Demonstrated by the channel video "Single Arm Cable Curls".
    template: {
      id: 'ch-single-arm-cable-curl',
      name: 'Single-Arm Cable Curl',
      sets: 3,
      reps: '10-12 each side',
      cue: 'Low cable, one handle, elbow pinned to your side and curl the hand to the shoulder - one arm at a time so the stronger side cannot take over',
      suggestedLoad: '10-20 kg',
      category: 'accessory',
      targetRegions: ['bicep', 'elbow'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Biceps brachii',
      secondaryMuscles: ['Brachialis', 'Forearm flexors'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Bicep Curl',
        cue: 'Same elbow position with a dumbbell, curl one arm at a time and lower slowly',
        suggestedLoad: '8-16 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'fullgym',
    // Demonstrated by the channel video "Cable Hip Abduction".
    template: {
      id: 'ch-cable-hip-abduction',
      name: 'Cable Hip Abduction',
      sets: 3,
      reps: '12-15 each side',
      cue: 'Ankle strap on the outside leg, stand tall holding the frame and sweep the leg out to the side - lead with the heel and keep the torso still rather than leaning away',
      suggestedLoad: '5-15 kg',
      category: 'accessory',
      targetRegions: ['glutes', 'hip_groin'],
      videoId: '',
      movementPattern: 'rehabilitation',
      primaryMuscle: 'Gluteus medius',
      secondaryMuscles: ['Gluteus minimus', 'Tensor fasciae latae'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'Banded Lateral Walk',
        cue: 'Band above the knees, half-squat and step sideways - same glute medius work with no machine',
        suggestedLoad: 'Light band',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Cable Hip Extensions".
    template: {
      id: 'ch-cable-hip-extension',
      name: 'Cable Hip Extension',
      sets: 3,
      reps: '12-15 each side',
      cue: 'Ankle strap on the working leg, face the frame and drive the leg back from the hip - squeeze the glute at the end and do not let the lower back arch to get further',
      suggestedLoad: '10-20 kg',
      category: 'accessory',
      targetRegions: ['glutes', 'hamstrings', 'hip_groin'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Gluteus maximus',
      secondaryMuscles: ['Hamstrings'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'Banded Glute Bridge',
        cue: 'On your back, band above the knees, drive the hips up and squeeze - same glute drive lying down',
        suggestedLoad: 'Light band',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'fullgym',
    // Demonstrated by the channel video "Cable Hip Flexion".
    template: {
      id: 'ch-cable-hip-flexion',
      name: 'Cable Hip Flexion',
      sets: 3,
      reps: '12-15 each side',
      cue: 'Ankle strap on the working leg, back to the frame, drive the knee up towards your chest against the resistance - stand tall and let the hip do the work, not a backward lean',
      suggestedLoad: '5-15 kg',
      category: 'accessory',
      targetRegions: ['quads', 'hip_groin', 'core_ribs'],
      videoId: '',
      movementPattern: 'rehabilitation',
      primaryMuscle: 'Iliopsoas',
      secondaryMuscles: ['Rectus femoris', 'Sartorius'],
      equipmentRequired: 'cable machine',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'Banded March',
        cue: 'Band around both feet, drive one knee up at a time - the same hip flexor drive standing on the spot',
        suggestedLoad: 'Light band',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Landmine Single Arm Rows".
    template: {
      id: 'ch-landmine-single-arm-row',
      name: 'Landmine Single-Arm Row',
      sets: 3,
      reps: '10-12 each side',
      cue: 'One end of the barbell in the corner, hinge over and row the sleeve to your hip with one hand - the arc of the bar keeps the shoulder in a comfortable line',
      suggestedLoad: '20-40 kg',
      category: 'accessory',
      targetRegions: ['lat_mid_back', 'upper_back', 'rear_shoulder'],
      videoId: '',
      movementPattern: 'pull',
      primaryMuscle: 'Latissimus dorsi',
      secondaryMuscles: ['Rhomboids', 'Rear deltoid', 'Biceps brachii'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Single-Arm Row',
        cue: 'Same hinge and same pull to the hip, with a dumbbell and a bench for support',
        suggestedLoad: '20-35 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Landmine Romanian Deadlifts".
    template: {
      id: 'ch-landmine-romanian-deadlift',
      name: 'Landmine Romanian Deadlift',
      sets: 3,
      reps: '8-10',
      cue: 'Hold the end of the barbell at your thighs, push the hips back with soft knees until the hamstrings pull, then drive the hips forward - the fixed arc keeps the bar tracking close',
      suggestedLoad: '30-60 kg',
      category: 'accessory',
      targetRegions: ['hamstrings', 'glutes', 'lower_back'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Hamstrings',
      secondaryMuscles: ['Glutes', 'Erector spinae', 'Core'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: false,
      swapAlternative: {
        name: 'DB Romanian Deadlift',
        cue: 'Same hip push with dumbbells in front of the thighs - stop when the hamstrings say so, not when the weights reach the floor',
        suggestedLoad: '20-40 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'deadlift',
    tier: 'fullgym',
    // Demonstrated by the channel video "Landmine Split Stance Romanian Deadlifts".
    template: {
      id: 'ch-landmine-split-stance-rdl',
      name: 'Landmine Split-Stance Romanian Deadlift',
      sets: 3,
      reps: '8-10 each side',
      cue: 'One foot back on its toe taking about a quarter of the weight, hinge over the front leg holding the barbell end - most of the load goes through the front hamstring',
      suggestedLoad: '25-50 kg',
      category: 'accessory',
      targetRegions: ['hamstrings', 'glutes', 'lower_back', 'hip_groin'],
      videoId: '',
      movementPattern: 'hinge',
      primaryMuscle: 'Hamstrings',
      secondaryMuscles: ['Glutes', 'Erector spinae', 'Core'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'DB Split-Stance Romanian Deadlift',
        cue: 'Same split stance and same hinge with dumbbells - back foot is a kickstand, not a second leg',
        suggestedLoad: '16-30 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'fullgym',
    // Demonstrated by the channel video "Landmine Split Squats".
    template: {
      id: 'ch-landmine-split-squat',
      name: 'Landmine Split Squat',
      sets: 3,
      reps: '8-10 each side',
      cue: 'Hold the barbell end at your chest in a split stance, drop the back knee towards the floor and drive up through the front heel - the bar in front helps you stay upright',
      suggestedLoad: '20-40 kg',
      category: 'accessory',
      targetRegions: ['quads', 'glutes', 'knee', 'hip_groin'],
      videoId: '',
      movementPattern: 'squat',
      primaryMuscle: 'Quadriceps',
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
      equipmentRequired: 'barbell',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Goblet Split Squat',
        cue: 'Same stance holding a dumbbell at the chest - front heel stays down the whole way',
        suggestedLoad: '12-24 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'fullgym',
    // Demonstrated by the channel video "Landmine Goblet Squats".
    template: {
      id: 'ch-landmine-goblet-squat',
      name: 'Landmine Goblet Squat',
      sets: 3,
      reps: '10-12',
      cue: 'Cradle the end of the barbell at your chest and squat between your feet - the arc of the bar pulls you slightly forward, which makes staying upright easier than a free weight',
      suggestedLoad: '25-50 kg',
      category: 'accessory',
      targetRegions: ['quads', 'glutes', 'knee'],
      videoId: '',
      movementPattern: 'squat',
      primaryMuscle: 'Quadriceps',
      secondaryMuscles: ['Glutes', 'Core', 'Upper back'],
      equipmentRequired: 'barbell',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Goblet Squat',
        cue: 'Same squat holding a dumbbell at the chest - elbows inside the knees at the bottom',
        suggestedLoad: '16-32 kg',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Bent Knee Calf Raises".
    template: {
      id: 'ch-bent-knee-calf-raise',
      name: 'Bent-Knee Calf Raise',
      sets: 3,
      reps: '15-20',
      cue: 'Stand with the knees softly bent and hold them there, then push through the balls of the feet - bending the knee takes the big calf muscle out and makes the soleus underneath do the work',
      suggestedLoad: 'Bodyweight',
      category: 'accessory',
      targetRegions: ['calf_shin', 'ankle_achilles'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Soleus',
      secondaryMuscles: ['Gastrocnemius', 'Tibialis posterior'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Calf Raise',
        cue: 'Straight-knee version - this one works the calf you can see rather than the one underneath it',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Bent Knee Single Leg Calf Raise".
    template: {
      id: 'ch-bent-knee-single-leg-calf-raise',
      name: 'Bent-Knee Single-Leg Calf Raise',
      sets: 3,
      reps: '10-15 each side',
      cue: 'One leg, knee softly bent and held there, rise onto the ball of the foot and lower slowly - hold something for balance so the ankle can work rather than the whole body fighting to stay still',
      suggestedLoad: 'Bodyweight',
      category: 'accessory',
      targetRegions: ['calf_shin', 'ankle_achilles'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Soleus',
      secondaryMuscles: ['Gastrocnemius', 'Tibialis posterior'],
      equipmentRequired: 'bodyweight',
      difficulty: 'intermediate',
      isUnilateral: true,
      swapAlternative: {
        name: 'Bent-Knee Calf Raise',
        cue: 'Both feet at once - same bent-knee position, half the load per side',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Seated Calf Raises".
    template: {
      id: 'ch-seated-calf-raise',
      name: 'Seated Calf Raise',
      sets: 3,
      reps: '15-20',
      cue: 'Sat down with the knees bent to a right angle and the feet flat, push through the balls of the feet and squeeze at the top - seated is the other way to reach the soleus',
      suggestedLoad: 'Bodyweight',
      category: 'accessory',
      targetRegions: ['calf_shin', 'ankle_achilles'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Soleus',
      secondaryMuscles: ['Tibialis posterior'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Bent-Knee Calf Raise',
        cue: 'Standing with a soft knee - the same muscle, with your bodyweight on it',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'ACCESSORIES',
    sessionType: 'squat',
    tier: 'dumbbells',
    // Demonstrated by the channel video "Weighted Seated Calf Raises".
    template: {
      id: 'ch-weighted-seated-calf-raise',
      name: 'Weighted Seated Calf Raise',
      sets: 3,
      reps: '12-15',
      cue: 'Sat with the knees bent to a right angle and a dumbbell resting on each thigh just above the knee, push through the balls of the feet and pause at the top',
      suggestedLoad: '10-20 kg',
      category: 'accessory',
      targetRegions: ['calf_shin', 'ankle_achilles'],
      videoId: '',
      movementPattern: 'push',
      primaryMuscle: 'Soleus',
      secondaryMuscles: ['Tibialis posterior'],
      equipmentRequired: 'dumbbells',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Seated Calf Raise',
        cue: 'Same position with nothing on the thighs - add the weight once fifteen are easy',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREHAB',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Tib Raises".
    template: {
      id: 'ch-tib-raise',
      name: 'Tib Raise',
      sets: 3,
      reps: '15-20',
      cue: 'Heels against a wall with the feet a little way out, lean back and pull the toes up towards the shins as far as they will go, then lower slowly - the muscle down the front of the shin, which almost nothing else trains',
      suggestedLoad: 'Bodyweight',
      category: 'prehab',
      targetRegions: ['calf_shin', 'ankle_achilles'],
      videoId: '',
      movementPattern: 'rehabilitation',
      primaryMuscle: 'Tibialis anterior',
      secondaryMuscles: ['Extensor digitorum longus'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: 'Seated Toe Raise',
        cue: 'Sat down, heels on the floor, lift the toes and hold for a second - the same shin work with no wall',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  // ───────────────────────────────────────────────────────────────────────────
  // THIRD BATCH — 10 more uploads. Five matched exercises the app already had;
  // these four are the movements it did not carry. All four are warm-up and
  // knee/hip rehab work, which is the part of the catalogue the channel is
  // filling in fastest.
  // ───────────────────────────────────────────────────────────────────────────
  {
    collection: 'PREHAB',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Banded VMO Extensions".
    template: {
      id: 'ch-banded-vmo-extension',
      name: 'Banded VMO Extension',
      sets: 3,
      reps: '15 each side',
      cue: 'Band behind the knee, stand with a soft bend and straighten the leg fully against it, squeezing the inner quad just above the knee for a second at the top - the last few degrees are the whole exercise',
      suggestedLoad: 'Light band',
      category: 'prehab',
      targetRegions: ['quads', 'knee'],
      videoId: '',
      movementPattern: 'rehabilitation',
      primaryMuscle: 'Vastus medialis',
      secondaryMuscles: ['Quadriceps'],
      equipmentRequired: 'resistance bands',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'VMO Wall Sit',
        cue: 'Narrow stance against the wall at 90 degrees and hold - the same inner-quad work without a band',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREP',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Leg Swings".
    template: {
      id: 'ch-leg-swing',
      name: 'Leg Swing',
      sets: 1,
      reps: '12 each leg',
      cue: 'Hold something steady and swing one leg forwards and back, letting the range build over the first few - loose and rhythmic, never forced to the end of range',
      suggestedLoad: 'Bodyweight',
      category: 'prep',
      targetRegions: ['hip_groin', 'hamstrings', 'quads'],
      videoId: '',
      movementPattern: 'mobility',
      primaryMuscle: 'Hip flexors',
      secondaryMuscles: ['Hamstrings', 'Glutes'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'Bodyweight Hip Hinge',
        cue: 'Slow hinges on the spot to warm the same hips and hamstrings without the swing',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREP',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Lateral Leg Swings".
    template: {
      id: 'ch-lateral-leg-swing',
      name: 'Lateral Leg Swing',
      sets: 1,
      reps: '12 each leg',
      cue: 'Facing your support, swing one leg across the body and out to the side - hips stay square and the torso stays still, so the movement happens at the hip and not the waist',
      suggestedLoad: 'Bodyweight',
      category: 'prep',
      targetRegions: ['hip_groin', 'glutes'],
      videoId: '',
      movementPattern: 'mobility',
      primaryMuscle: 'Hip adductors',
      secondaryMuscles: ['Gluteus medius', 'Hip flexors'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: true,
      swapAlternative: {
        name: 'Leg Swing',
        cue: 'Forwards and back instead of across - the same hip, the other direction',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
  {
    collection: 'PREHAB',
    sessionType: 'squat',
    tier: 'bodyweight',
    // Demonstrated by the channel video "Seated Butterflies".
    template: {
      id: 'ch-seated-butterfly',
      name: 'Seated Butterfly',
      sets: 2,
      reps: '30-45 seconds',
      cue: 'Sat down, soles of the feet together and heels drawn towards you, let the knees settle outwards under their own weight - press gently with the elbows only if it stays comfortable',
      suggestedLoad: 'Bodyweight',
      category: 'prehab',
      targetRegions: ['hip_groin', 'glutes'],
      videoId: '',
      movementPattern: 'mobility',
      primaryMuscle: 'Hip adductors',
      secondaryMuscles: ['Gluteus medius'],
      equipmentRequired: 'bodyweight',
      difficulty: 'beginner',
      isUnilateral: false,
      swapAlternative: {
        name: '90/90 Hip Switch',
        cue: 'Sat with both knees bent at right angles, rotate the pair side to side - the same hips, moving rather than held',
        suggestedLoad: 'Bodyweight',
      },
    },
  },
];
