import type { ExerciseTemplate } from './exercise-db';
import type { PainRegion } from './store';

/**
 * THE EXERCISE LIBRARY, AS RECORDS.
 *
 * One record per exercise in docs/EXERCISE-LIBRARY.md, which is the source of
 * truth Archie supplied. tests/exercise-library.check.mjs parses that document
 * at run time and compares it against this file, so the two cannot drift: add a
 * row to the document without adding a record here and the check fails, and the
 * other way round.
 *
 * NOTHING IMPORTS THIS FILE YET. It is built beside the existing engine and
 * wired up later, one session type at a time.
 *
 * WHY THESE EXTEND ExerciseTemplate
 * ─────────────────────────────────
 * Progression, set logging and the session screen already know how to read an
 * ExerciseTemplate. A library record IS one, with four extra facts the document
 * gives us: the pattern it belongs to, the level it starts at, the kit it needs
 * and the job it does in a session. Nothing downstream has to learn a new shape.
 *
 * WHY SOME IDS LOOK NOTHING LIKE THE OTHERS
 * ─────────────────────────────────────────
 * Every load, every rep count and every progression a person has ever logged is
 * filed under the id of the exercise they did. So where a record is the same
 * movement done with the same implement as an exercise the app already has, the
 * record keeps that exercise's id and the person's history carries straight
 * over. 89 of the 160 records do. The rest are movements the app has never had,
 * or a genuinely different variant of one it has (a deficit, a pause, a band, a
 * different bar), and those get a fresh `lib-<pattern>-<name>` id, because
 * serving somebody their barbell deadlift weight on a snatch-grip deficit
 * deadlift would be worse than starting them fresh.
 *
 * Which is which was settled from the approved scope document: its "exact
 * match" and "same movement and kit, only a rename or a re-file is needed"
 * lists keep their ids; its "different kit, missing modifier or different
 * variant" list and its "no template at all" list get new ones. Two deliberate
 * departures from that rule, both written down so they can be argued with:
 *
 *   - Kettlebell Goblet Squats keeps sq-main-db (Goblet Squat). The scope
 *     document calls it a different variant because the existing template is
 *     cued with a dumbbell, but decision 5 says a dumbbell may stand in for a
 *     kettlebell on exactly this exercise, so by the owner's own ruling it is
 *     the same implement. It is also a main lift, so the loads people have
 *     logged against it are the ones worth keeping.
 *   - Box Step Downs does NOT keep ph-r-kn-2 (Slow Step-Down), which the scope
 *     document offers as its stand-in. That template is Restore content, and
 *     Restore is explicitly not governed by this list, so it keeps serving
 *     under its own name. One id cannot be two exercises with two names.
 *
 * Several of the reused ids have duplicates elsewhere in the catalogue (the
 * same movement filed again under another equipment tier). Those are merged in
 * a later phase, which copies progress forward onto the surviving id; nothing
 * here has to choose between them beyond picking the survivor.
 *
 * WHY movementPattern IS STILL HERE ALONGSIDE pattern
 * ───────────────────────────────────────────────────
 * They answer different questions. `pattern` is the library's own filing: one
 * of the six the document uses, and the thing a session slot asks for.
 * `movementPattern` is the older, finer description that loaded-hinge
 * detection, swap suggestions and session diversity all read. A carry and a
 * plank are both `core` to the library and are not the same movement at all.
 *
 * CONTENT IS NOT AUTHORED YET
 * ───────────────────────────
 * Cues, sets, reps, loads, muscles, regions and videos are placeholders in this
 * step and are filled in the next one. That is why every record spreads
 * PLACEHOLDER_CONTENT.
 *
 * `equipmentRequired` IS A HOLDING ANSWER
 * ───────────────────────────────────────
 * `kit` is the real one, and the next step teaches the equipment gate to read
 * it. Until then every record says 'bodyweight' if it needs nothing and
 * 'fullgym' if it needs anything at all, because that is the direction of error
 * that costs nobody a session: an exercise hidden from somebody who could have
 * done it, rather than offered to somebody who cannot.
 */

/** The six movement patterns the library files everything under. */
export type LibraryPattern = 'push' | 'pull' | 'hinge' | 'squat' | 'lunge' | 'core';

/** Beginner 1, Intermediate 2, Advanced 3, Athlete 4 — the onboarding answers. */
export type LibraryLevel = 1 | 2 | 3 | 4;

/** The onboarding wording for each level, for anything that shows it. */
export const LIBRARY_LEVEL_NAMES: Record<LibraryLevel, string> = {
  1: 'Beginner',
  2: 'Intermediate',
  3: 'Advanced',
  4: 'Athlete',
};

/**
 * Every named piece of kit in the library, as one short key each.
 *
 * "Weight Plates" and "Weight Plate" are both `plates`; a block and a plate are
 * interchangeable wherever the document offers the choice, so they stay two
 * keys and the record asks for either.
 */
export const KIT_KEYS = [
  'plates',
  'blocks',
  'bench',
  'box',
  'band',
  'dumbbell',
  'kettlebell',
  'barbell',
  'landmine',
  'corner',
  'rack',
  'trx',
  'medball',
  'slamball',
  'cable',
  'latpulldown',
  'pullupbar',
  'trapbar',
  'abwheel',
  'doorframe',
  'sled',
  'assaultbike',
  'treadmill',
  'rower',
  'rope',
] as const;

export type KitKey = (typeof KIT_KEYS)[number];

/**
 * What an exercise needs, as an AND of ORs.
 *
 * Each inner list is one requirement that any of its keys satisfies, and every
 * requirement has to be met. So a Landmine Press is
 * `[['barbell'], ['landmine', 'corner']]`: you need the bar, and you need
 * either the attachment or a corner to wedge it into. An empty list means the
 * exercise needs nothing at all, which is how the document's "Bodyweight" reads.
 */
export type KitRequirement = readonly (readonly KitKey[])[];

/**
 * What job the exercise does in a session.
 *
 * `main` leads a pattern slot and carries the load; `accessory` supports it;
 * `power` is the jumps, throws and slams, which the document keeps at Athlete
 * level only (decision 8) and which fill the power block rather than a pattern
 * slot.
 */
export type LibraryRole = 'main' | 'accessory' | 'power';

export interface LibraryExercise extends ExerciseTemplate {
  /** The name exactly as docs/EXERCISE-LIBRARY.md spells it. */
  libraryName: string;
  pattern: LibraryPattern;
  /**
   * The second pattern this exercise is also listed under.
   *
   * Used once. The document lists "Squat Jump" under Squat and "Squat Jumps"
   * under Lunge, and says in its own notes that they are the same movement. One
   * record, both patterns, so a Lunge slot can still reach it and a person who
   * meets it in both never sees it twice under two names.
   */
  alsoPattern?: LibraryPattern;
  /** The spelling the document uses for the second listing. */
  alsoLibraryName?: string;
  level: LibraryLevel;
  kit: KitRequirement;
  role: LibraryRole;
  /**
   * Authored safety tags, unioned with the name rules in exercise-safety.
   * Filled in the content step; deliberately empty here.
   */
  stress?: readonly string[];
}

export interface ConditioningExercise extends ExerciseTemplate {
  libraryName: string;
  kit: KitRequirement;
  /**
   * Kit that makes the exercise better but is not needed to do it.
   *
   * Skipping only. Decision 7 says it is with a rope or on the spot, so a rope
   * can never be a reason to withhold it.
   */
  optionalKit?: readonly KitKey[];
  role: 'conditioning';
  stress?: readonly string[];
}

/**
 * Stand-in content until the next step authors the real thing.
 *
 * A function, not a shared object, so no two records end up pointing at the
 * same targetRegions array.
 */
const PLACEHOLDER_CONTENT = (): Pick<
  ExerciseTemplate,
  'sets' | 'reps' | 'cue' | 'suggestedLoad' | 'targetRegions' | 'videoId'
> => ({
  sets: 3,
  reps: '',
  cue: '',
  suggestedLoad: '',
  targetRegions: [] as PainRegion[],
  videoId: '',
});

/** Both patterns an exercise is filed under, which is two for exactly one of them. */
export function patternsOf(exercise: LibraryExercise): LibraryPattern[] {
  return exercise.alsoPattern ? [exercise.pattern, exercise.alsoPattern] : [exercise.pattern];
}

/** Every spelling the document uses for an exercise. */
export function libraryNamesOf(exercise: LibraryExercise): string[] {
  return exercise.alsoLibraryName
    ? [exercise.libraryName, exercise.alsoLibraryName]
    : [exercise.libraryName];
}

/** The records filed under a pattern, including the one filed under two. */
export function libraryByPattern(pattern: LibraryPattern): LibraryExercise[] {
  return LIBRARY_EXERCISES.filter((e) => patternsOf(e).includes(pattern));
}

export const LIBRARY_EXERCISES: readonly LibraryExercise[] = [
  // ─── PUSH (24) ──────────────────────────────────────────────
  {
    id: 'lib-push-kneeling-press-ups',
    name: 'Kneeling Press Ups',
    libraryName: 'Kneeling Press Ups',
    pattern: 'push',
    level: 1,
    kit: [],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-push-kneeling-incline-press-ups',
    name: 'Kneeling Incline Press Ups',
    libraryName: 'Kneeling Incline Press Ups',
    pattern: 'push',
    level: 1,
    kit: [['bench', 'plates']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'cond-bw-e-2b',
    name: 'Bench Press Ups',
    libraryName: 'Bench Press Ups',
    pattern: 'push',
    level: 1,
    kit: [['bench']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-push-banded-serratus-punch',
    name: 'Banded Serratus Punch',
    libraryName: 'Banded Serratus Punch',
    pattern: 'push',
    level: 1,
    kit: [['band']],
    role: 'accessory',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-push-plate-squeeze-press',
    name: 'Plate Squeeze Press',
    libraryName: 'Plate Squeeze Press',
    pattern: 'push',
    level: 1,
    kit: [['plates']],
    role: 'accessory',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-push-plate-bench-press',
    name: 'Plate Bench Press',
    libraryName: 'Plate Bench Press',
    pattern: 'push',
    level: 1,
    kit: [['plates'], ['bench']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-main-bw',
    name: 'Push Up',
    libraryName: 'Push Up',
    pattern: 'push',
    level: 2,
    kit: [],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-db-12',
    name: 'Seated Dumbbell Press',
    libraryName: 'Seated Dumbbell Press',
    pattern: 'push',
    level: 2,
    kit: [['dumbbell'], ['bench']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'cond-db-e-2b',
    name: 'Dumbbell Floor Press',
    libraryName: 'Dumbbell Floor Press',
    pattern: 'push',
    level: 2,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-main-db',
    name: 'Dumbbell Bench Press',
    libraryName: 'Dumbbell Bench Press',
    pattern: 'push',
    level: 2,
    kit: [['dumbbell'], ['bench']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-db-13',
    name: 'Standing Dumbbell Press',
    libraryName: 'Standing Dumbbell Press',
    pattern: 'push',
    level: 2,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-fg-7',
    name: 'Incline Dumbbell Bench Press',
    libraryName: 'Incline Dumbbell Bench Press',
    pattern: 'push',
    level: 2,
    kit: [['dumbbell'], ['bench']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-bw-6',
    name: 'Bench Dips',
    libraryName: 'Bench Dips',
    pattern: 'push',
    level: 2,
    kit: [['bench', 'plates']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-bw-13',
    name: 'Deficit Press Ups',
    libraryName: 'Deficit Press Ups',
    pattern: 'push',
    level: 3,
    kit: [['plates', 'blocks']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-push-decline-press-ups',
    name: 'Decline Press Ups',
    libraryName: 'Decline Press Ups',
    pattern: 'push',
    level: 3,
    kit: [['bench', 'plates']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-alternating-dumbbell-bench-press',
    name: 'Alternating Dumbbell Bench Press',
    libraryName: 'Alternating Dumbbell Bench Press',
    pattern: 'push',
    level: 3,
    kit: [['dumbbell'], ['bench']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-single-arm-dumbbell-overhead-pre',
    name: 'Single Arm Dumbbell Press',
    libraryName: 'Single Arm Dumbbell Press',
    pattern: 'push',
    level: 3,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-alternating-dumbbell-overhead-pr',
    name: 'Alternating Dumbbell Shoulder Press',
    libraryName: 'Alternating Dumbbell Shoulder Press',
    pattern: 'push',
    level: 3,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-fg-22',
    name: 'Landmine Press',
    libraryName: 'Landmine Press',
    pattern: 'push',
    level: 3,
    kit: [['barbell'], ['landmine', 'corner']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-push-trx-push-ups',
    name: 'TRX Push Ups',
    libraryName: 'TRX Push Ups',
    pattern: 'push',
    level: 4,
    kit: [['trx']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-push-barbell-floor-press',
    name: 'Barbell Floor Press',
    libraryName: 'Barbell Floor Press',
    pattern: 'push',
    level: 4,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-push-band-resisted-barbell-press',
    name: 'Band Resisted Barbell Press',
    libraryName: 'Band Resisted Barbell Press',
    pattern: 'push',
    level: 4,
    kit: [['barbell'], ['plates'], ['band'], ['bench'], ['rack']],
    role: 'main',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-supine-med-ball-throw',
    name: 'Supine Medball Throws',
    libraryName: 'Supine Medball Throws',
    pattern: 'push',
    level: 4,
    kit: [['medball']],
    role: 'power',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'ch-med-ball-floor-chest-pass',
    name: 'Medball Floor Chest Pass',
    libraryName: 'Medball Floor Chest Pass',
    pattern: 'push',
    level: 4,
    kit: [['medball']],
    role: 'power',
    movementPattern: 'push',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  // ─── PULL (25) ──────────────────────────────────────────────
  {
    id: 'bn-mech-bw-1',
    name: 'Band Pull Aparts',
    libraryName: 'Band Pull Aparts',
    pattern: 'pull',
    level: 1,
    kit: [['band']],
    role: 'accessory',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-pull-door-frame-rows',
    name: 'Door Frame Rows',
    libraryName: 'Door Frame Rows',
    pattern: 'pull',
    level: 1,
    kit: [['doorframe']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-bw-8',
    name: 'Banded Face Pulls',
    libraryName: 'Banded Face Pulls',
    pattern: 'pull',
    level: 1,
    kit: [['band']],
    role: 'accessory',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'dl-acc-fg-9',
    name: 'Cable Face Pulls',
    libraryName: 'Cable Face Pulls',
    pattern: 'pull',
    level: 1,
    kit: [['cable']],
    role: 'accessory',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'ch-seated-single-arm-cable-row',
    name: 'Seated Single Arm Rows',
    libraryName: 'Seated Single Arm Rows',
    pattern: 'pull',
    level: 1,
    kit: [['cable']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-fg-6',
    name: 'Seated Close Grip Rows',
    libraryName: 'Seated Close Grip Rows',
    pattern: 'pull',
    level: 1,
    kit: [['cable']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-seated-wide-grip-cable-row',
    name: 'Seated Wide Grip Rows',
    libraryName: 'Seated Wide Grip Rows',
    pattern: 'pull',
    level: 1,
    kit: [['cable']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-pull-cable-single-arm-rows',
    name: 'Cable Single Arm Rows',
    libraryName: 'Cable Single Arm Rows',
    pattern: 'pull',
    level: 2,
    kit: [['cable']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-fg-4',
    name: 'Lat Pulldowns',
    libraryName: 'Lat Pulldowns',
    pattern: 'pull',
    level: 2,
    kit: [['latpulldown', 'cable']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-pull-trx-rows',
    name: 'TRX Rows',
    libraryName: 'TRX Rows',
    pattern: 'pull',
    level: 2,
    kit: [['trx']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-pull-trx-face-pulls',
    name: 'TRX Face Pulls',
    libraryName: 'TRX Face Pulls',
    pattern: 'pull',
    level: 2,
    kit: [['trx']],
    role: 'accessory',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-pull-bench-dumbbell-face-pulls',
    name: 'Bench Dumbbell Face Pulls',
    libraryName: 'Bench Dumbbell Face Pulls',
    pattern: 'pull',
    level: 2,
    kit: [['dumbbell'], ['bench']],
    role: 'accessory',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'bn-acc-db-15',
    name: 'Chest Supported Dumbbell Row',
    libraryName: 'Chest Supported Dumbbell Row',
    pattern: 'pull',
    level: 2,
    kit: [['dumbbell'], ['bench']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-acc-db-2',
    name: 'Bent Over Dumbbell Rows',
    libraryName: 'Bent Over Dumbbell Rows',
    pattern: 'pull',
    level: 3,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-db-1',
    name: 'Single Arm Dumbbell Rows',
    libraryName: 'Single Arm Dumbbell Rows',
    pattern: 'pull',
    level: 3,
    kit: [['dumbbell'], ['bench']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-landmine-single-arm-row',
    name: 'Landmine Single Arm Rows',
    libraryName: 'Landmine Single Arm Rows',
    pattern: 'pull',
    level: 3,
    kit: [['barbell'], ['landmine', 'corner']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-gorilla-row',
    name: 'Gorilla Rows',
    libraryName: 'Gorilla Rows',
    pattern: 'pull',
    level: 3,
    kit: [['kettlebell', 'dumbbell']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'wub-fg-row',
    name: 'Barbell Row',
    libraryName: 'Barbell Row',
    pattern: 'pull',
    level: 3,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-trap-bar-row',
    name: 'Trapbar Rows',
    libraryName: 'Trapbar Rows',
    pattern: 'pull',
    level: 3,
    kit: [['trapbar'], ['plates']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-pull-rack-rows',
    name: 'Rack Rows',
    libraryName: 'Rack Rows',
    pattern: 'pull',
    level: 3,
    kit: [['barbell'], ['rack']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-pull-elevated-feet-rack-rows',
    name: 'Elevated Feet Rack Rows',
    libraryName: 'Elevated Feet Rack Rows',
    pattern: 'pull',
    level: 4,
    kit: [['box', 'bench'], ['rack'], ['barbell']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-pull-band-assisted-chin-up',
    name: 'Band Assisted Chin Up',
    libraryName: 'Band Assisted Chin Up',
    pattern: 'pull',
    level: 4,
    kit: [['pullupbar'], ['band']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-acc-fg-20',
    name: 'Chin Ups',
    libraryName: 'Chin Ups',
    pattern: 'pull',
    level: 4,
    kit: [['pullupbar']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-acc-bw-5',
    name: 'Pull Ups',
    libraryName: 'Pull Ups',
    pattern: 'pull',
    level: 4,
    kit: [['pullupbar']],
    role: 'main',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'bn-neuro-fg-2',
    name: 'Medball Slams',
    libraryName: 'Medball Slams',
    pattern: 'pull',
    level: 4,
    kit: [['slamball']],
    role: 'power',
    movementPattern: 'pull',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  // ─── HINGE (31) ─────────────────────────────────────────────
  {
    id: 'dl-mech-bw-4',
    name: 'Wall Hip Hinge',
    libraryName: 'Wall Hip Hinge',
    pattern: 'hinge',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'hinge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'sq-acc-bw-2',
    name: 'Glute Bridge',
    libraryName: 'Glute Bridge',
    pattern: 'hinge',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'hinge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'dl-acc-bw-4',
    name: 'Banded Good Mornings',
    libraryName: 'Banded Good Mornings',
    pattern: 'hinge',
    level: 1,
    kit: [['band']],
    role: 'accessory',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'ch-kb-romanian-deadlift',
    name: 'Kettlebell Romanian Deadlift',
    libraryName: 'Kettlebell Romanian Deadlift',
    pattern: 'hinge',
    level: 1,
    kit: [['kettlebell']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-kettlebell-deadlift',
    name: 'Kettlebell Deadlift',
    libraryName: 'Kettlebell Deadlift',
    pattern: 'hinge',
    level: 1,
    kit: [['kettlebell']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-acc-fg-4',
    name: 'Cable Pull Through',
    libraryName: 'Cable Pull Through',
    pattern: 'hinge',
    level: 2,
    kit: [['cable']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-cable-romanian-deadlift',
    name: 'Cable Romanian Deadlift',
    libraryName: 'Cable Romanian Deadlift',
    pattern: 'hinge',
    level: 2,
    kit: [['cable']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-db-split-stance-romanian-deadlif',
    name: 'Split Stance Romanian Deadlift',
    libraryName: 'Split Stance Romanian Deadlift',
    pattern: 'hinge',
    level: 2,
    kit: [['dumbbell', 'kettlebell']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-acc-db-5',
    name: 'Single Leg Romanian Deadlift',
    libraryName: 'Single Leg Romanian Deadlift',
    pattern: 'hinge',
    level: 2,
    kit: [['dumbbell', 'kettlebell']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-deficit-kettlebell-deadlift',
    name: 'Deficit Kettlebell Deadlift',
    libraryName: 'Deficit Kettlebell Deadlift',
    pattern: 'hinge',
    level: 2,
    kit: [['kettlebell'], ['plates', 'blocks']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-landmine-romanian-deadlift',
    name: 'Landmine Romanian Deadlift',
    libraryName: 'Landmine Romanian Deadlift',
    pattern: 'hinge',
    level: 2,
    kit: [['barbell'], ['landmine', 'corner']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-landmine-split-stance-rdl',
    name: 'Landmine Split Stance Romanian Deadlift',
    libraryName: 'Landmine Split Stance Romanian Deadlift',
    pattern: 'hinge',
    level: 2,
    kit: [['barbell'], ['landmine', 'corner']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-trapbar-deadlift-high-handles',
    name: 'Trapbar Deadlift (high handles)',
    libraryName: 'Trapbar Deadlift (high handles)',
    pattern: 'hinge',
    level: 2,
    kit: [['trapbar'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-trapbar-deadlift-low-handles',
    name: 'Trapbar Deadlift (low handles)',
    libraryName: 'Trapbar Deadlift (low handles)',
    pattern: 'hinge',
    level: 3,
    kit: [['trapbar'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-trap-bar-romanian-deadlift',
    name: 'Trapbar Romanian Deadlift',
    libraryName: 'Trapbar Romanian Deadlift',
    pattern: 'hinge',
    level: 3,
    kit: [['trapbar'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-acc-fg-6',
    name: 'Rack Pull',
    libraryName: 'Rack Pull',
    pattern: 'hinge',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-fg-18',
    name: 'Barbell Good Mornings',
    libraryName: 'Barbell Good Mornings',
    pattern: 'hinge',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-main-fg',
    name: 'Barbell Deadlift',
    libraryName: 'Barbell Deadlift',
    pattern: 'hinge',
    level: 3,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-sumo-deadlift',
    name: 'Sumo Deadlift',
    libraryName: 'Sumo Deadlift',
    pattern: 'hinge',
    level: 3,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-pause-deadlifts',
    name: 'Pause Deadlifts',
    libraryName: 'Pause Deadlifts',
    pattern: 'hinge',
    level: 3,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-single-leg-romanian-deadlift',
    name: 'Single Leg Romanian Deadlift',
    libraryName: 'Single Leg Romanian Deadlift',
    pattern: 'hinge',
    level: 3,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-reeves-deadlift',
    name: 'Reeves Deadlift',
    libraryName: 'Reeves Deadlift',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-suitcase-deadlift',
    name: 'Suitcase Deadlift',
    libraryName: 'Suitcase Deadlift',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-band-resisted-deadlifts',
    name: 'Band Resisted Deadlifts',
    libraryName: 'Band Resisted Deadlifts',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates'], ['band']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-snatch-grip-deficit-deadlift',
    name: 'Snatch Grip Deficit Deadlift',
    libraryName: 'Snatch Grip Deficit Deadlift',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-hinge-deficit-barbell-deadlift',
    name: 'Deficit Barbell Deadlift',
    libraryName: 'Deficit Barbell Deadlift',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates'], ['plates', 'blocks']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-neuro-db',
    name: 'Kettlebell Swings',
    libraryName: 'Kettlebell Swings',
    pattern: 'hinge',
    level: 4,
    kit: [['kettlebell']],
    role: 'power',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'lib-hinge-deficit-romanian-deadlift',
    name: 'Deficit Romanian Deadlift',
    libraryName: 'Deficit Romanian Deadlift',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates'], ['plates', 'blocks']],
    role: 'main',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-neuro-bw',
    name: 'Broad Jumps',
    libraryName: 'Broad Jumps',
    pattern: 'hinge',
    level: 4,
    kit: [],
    role: 'power',
    movementPattern: 'hinge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'lib-hinge-banded-broad-jumps',
    name: 'Banded Broad Jumps',
    libraryName: 'Banded Broad Jumps',
    pattern: 'hinge',
    level: 4,
    kit: [['band']],
    role: 'power',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'lib-hinge-high-pulls',
    name: 'High Pulls',
    libraryName: 'High Pulls',
    pattern: 'hinge',
    level: 4,
    kit: [['barbell'], ['plates']],
    role: 'power',
    movementPattern: 'hinge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  // ─── SQUAT (25) ─────────────────────────────────────────────
  {
    id: 'lib-squat-assisted-squats',
    name: 'Assisted Squats',
    libraryName: 'Assisted Squats',
    pattern: 'squat',
    level: 1,
    kit: [['trx']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-main-bw',
    name: 'Bodyweight Squats',
    libraryName: 'Bodyweight Squats',
    pattern: 'squat',
    level: 1,
    kit: [],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-bw-4',
    name: 'Wall Sit',
    libraryName: 'Wall Sit',
    pattern: 'squat',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'squat',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-squat-box-squats',
    name: 'Box Squats',
    libraryName: 'Box Squats',
    pattern: 'squat',
    level: 1,
    kit: [['box', 'bench']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-kettlebell-box-squats',
    name: 'Kettlebell Box Squats',
    libraryName: 'Kettlebell Box Squats',
    pattern: 'squat',
    level: 2,
    kit: [['box', 'bench'], ['dumbbell', 'kettlebell']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-main-db',
    name: 'Kettlebell Goblet Squats',
    libraryName: 'Kettlebell Goblet Squats',
    pattern: 'squat',
    level: 2,
    kit: [['kettlebell']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'cond-db-e-6b',
    name: 'Dumbbell Front Squats',
    libraryName: 'Dumbbell Front Squats',
    pattern: 'squat',
    level: 2,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-landmine-goblet-squat',
    name: 'Landmine Goblet Squats',
    libraryName: 'Landmine Goblet Squats',
    pattern: 'squat',
    level: 2,
    kit: [['barbell'], ['landmine', 'corner']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-main-fg',
    name: 'Barbell Back Squat',
    libraryName: 'Barbell Back Squat',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-zercher-squat',
    name: 'Zercher Squat',
    libraryName: 'Zercher Squat',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-zombie-squat',
    name: 'Zombie Squat',
    libraryName: 'Zombie Squat',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-fg-11',
    name: 'Barbell Front Squat',
    libraryName: 'Barbell Front Squat',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-pause-squats',
    name: 'Pause Squats',
    libraryName: 'Pause Squats',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-pin-squats',
    name: 'Pin Squats',
    libraryName: 'Pin Squats',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-box-squat',
    name: 'Barbell Box Squats',
    libraryName: 'Barbell Box Squats',
    pattern: 'squat',
    level: 3,
    kit: [['barbell'], ['rack'], ['box', 'bench']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-band-resisted-back-squats',
    name: 'Band Resisted Back Squats',
    libraryName: 'Band Resisted Back Squats',
    pattern: 'squat',
    level: 4,
    kit: [['barbell'], ['plates'], ['band'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-squat-band-resisted-front-squats',
    name: 'Band Resisted Front Squats',
    libraryName: 'Band Resisted Front Squats',
    pattern: 'squat',
    level: 4,
    kit: [['barbell'], ['plates'], ['band'], ['rack']],
    role: 'main',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-neuro-bw',
    name: 'Squat Jump',
    libraryName: 'Squat Jump',
    pattern: 'squat',
    alsoPattern: 'lunge',
    alsoLibraryName: 'Squat Jumps',
    level: 4,
    kit: [],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'lib-squat-slamball-squat-jumps',
    name: 'Slamball Squat Jumps',
    libraryName: 'Slamball Squat Jumps',
    pattern: 'squat',
    level: 4,
    kit: [['slamball']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'ch-db-squat-jump',
    name: 'Dumbbell Jump Squats',
    libraryName: 'Dumbbell Jump Squats',
    pattern: 'squat',
    level: 4,
    kit: [['dumbbell']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'lib-squat-barbell-jump-squats',
    name: 'Barbell Jump Squats',
    libraryName: 'Barbell Jump Squats',
    pattern: 'squat',
    level: 4,
    kit: [['barbell']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'ch-trap-bar-jump',
    name: 'Trapbar Jump Squats',
    libraryName: 'Trapbar Jump Squats',
    pattern: 'squat',
    level: 4,
    kit: [['trapbar']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'sq-neuro-db',
    name: 'Box Jumps',
    libraryName: 'Box Jumps',
    pattern: 'squat',
    level: 4,
    kit: [['box', 'bench']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'ch-seated-box-jump',
    name: 'Seated Box Jumps',
    libraryName: 'Seated Box Jumps',
    pattern: 'squat',
    level: 4,
    kit: [['box', 'bench'], ['bench']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'sq-pwr-neuro-fg',
    name: 'Depth Jumps',
    libraryName: 'Depth Jumps',
    pattern: 'squat',
    level: 4,
    kit: [['box', 'bench']],
    role: 'power',
    movementPattern: 'squat',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  // ─── LUNGE (26) ─────────────────────────────────────────────
  {
    id: 'lib-lunge-assisted-bulgarian-split-squats',
    name: 'Assisted Bulgarian Split Squats',
    libraryName: 'Assisted Bulgarian Split Squats',
    pattern: 'lunge',
    level: 1,
    kit: [['trx']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-assisted-reverse-lunges',
    name: 'Assisted Reverse Lunges',
    libraryName: 'Assisted Reverse Lunges',
    pattern: 'lunge',
    level: 1,
    kit: [['trx']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-bw-10',
    name: 'Side Lunge',
    libraryName: 'Side Lunge',
    pattern: 'lunge',
    level: 1,
    kit: [],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'cond-bw-e-2a',
    name: 'Alternating Reverse Lunges',
    libraryName: 'Alternating Reverse Lunges',
    pattern: 'lunge',
    level: 1,
    kit: [],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'dl-fin-bw-e',
    name: 'Walking Lunges',
    libraryName: 'Walking Lunges',
    pattern: 'lunge',
    level: 1,
    kit: [],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'cond-fg-e-4b',
    name: 'Box Step Ups',
    libraryName: 'Box Step Ups',
    pattern: 'lunge',
    level: 1,
    kit: [['box', 'bench']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-box-step-downs',
    name: 'Box Step Downs',
    libraryName: 'Box Step Downs',
    pattern: 'lunge',
    level: 1,
    kit: [['box', 'bench']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-bw-8',
    name: 'Curtsy Lunge',
    libraryName: 'Curtsy Lunge',
    pattern: 'lunge',
    level: 1,
    kit: [],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'wlb-bw-split',
    name: 'Bulgarian Split Squat',
    libraryName: 'Bulgarian Split Squat',
    pattern: 'lunge',
    level: 2,
    kit: [['bench']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-landmine-split-squat',
    name: 'Landmine Split Squats',
    libraryName: 'Landmine Split Squats',
    pattern: 'lunge',
    level: 2,
    kit: [['barbell'], ['landmine', 'corner']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-kb-side-lunge',
    name: 'Kettlebell Side Lunge',
    libraryName: 'Kettlebell Side Lunge',
    pattern: 'lunge',
    level: 2,
    kit: [['kettlebell']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-kettlebell-reverse-lunges',
    name: 'Kettlebell Reverse Lunges',
    libraryName: 'Kettlebell Reverse Lunges',
    pattern: 'lunge',
    level: 2,
    kit: [['kettlebell']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'cond-db-e-3b',
    name: 'Dumbbell Alternating Reverse Lunges',
    libraryName: 'Dumbbell Alternating Reverse Lunges',
    pattern: 'lunge',
    level: 2,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-fg-1',
    name: 'Dumbbell Walking Lunges',
    libraryName: 'Dumbbell Walking Lunges',
    pattern: 'lunge',
    level: 2,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-deficit-split-squats',
    name: 'Deficit Split Squats',
    libraryName: 'Deficit Split Squats',
    pattern: 'lunge',
    level: 2,
    kit: [],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-kettlebell-curtsy-lunge',
    name: 'Kettlebell Curtsy Lunge',
    libraryName: 'Kettlebell Curtsy Lunge',
    pattern: 'lunge',
    level: 3,
    kit: [['kettlebell']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-dumbbell-curtsy-lunge',
    name: 'Dumbbell Curtsy Lunge',
    libraryName: 'Dumbbell Curtsy Lunge',
    pattern: 'lunge',
    level: 3,
    kit: [['dumbbell']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'sq-acc-db-1',
    name: 'Dumbbell Bulgarian Split Squat',
    libraryName: 'Dumbbell Bulgarian Split Squat',
    pattern: 'lunge',
    level: 3,
    kit: [['dumbbell'], ['bench', 'plates']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-box-step-over',
    name: 'Box Step Over',
    libraryName: 'Box Step Over',
    pattern: 'lunge',
    level: 3,
    kit: [['box', 'bench']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-kettlebell-box-step-over',
    name: 'Kettlebell Box Step Over',
    libraryName: 'Kettlebell Box Step Over',
    pattern: 'lunge',
    level: 3,
    kit: [['kettlebell'], ['box', 'bench']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'lib-lunge-barbell-reverse-lunges',
    name: 'Barbell Reverse Lunges',
    libraryName: 'Barbell Reverse Lunges',
    pattern: 'lunge',
    level: 3,
    kit: [['barbell'], ['plates'], ['rack']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'wlb-fg-split',
    name: 'Barbell Bulgarian Split Squats',
    libraryName: 'Barbell Bulgarian Split Squats',
    pattern: 'lunge',
    level: 3,
    kit: [['barbell'], ['plates'], ['bench'], ['rack']],
    role: 'main',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'main',
  },
  {
    id: 'ch-skater-jump',
    name: 'Skater Jumps',
    libraryName: 'Skater Jumps',
    pattern: 'lunge',
    level: 4,
    kit: [],
    role: 'power',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'ch-split-squat-jump',
    name: 'Split Squat Jumps',
    libraryName: 'Split Squat Jumps',
    pattern: 'lunge',
    level: 4,
    kit: [],
    role: 'power',
    movementPattern: 'lunge',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'ch-db-split-squat-jump',
    name: 'Dumbbell Split Squat Jumps',
    libraryName: 'Dumbbell Split Squat Jumps',
    pattern: 'lunge',
    level: 4,
    kit: [['dumbbell']],
    role: 'power',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  {
    id: 'lib-lunge-slamball-split-jumps',
    name: 'Slamball Split Jumps',
    libraryName: 'Slamball Split Jumps',
    pattern: 'lunge',
    level: 4,
    kit: [['slamball']],
    role: 'power',
    movementPattern: 'lunge',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'neuro',
  },
  // ─── CORE (29) ──────────────────────────────────────────────
  {
    id: 'ch-plank',
    name: 'Plank',
    libraryName: 'Plank',
    pattern: 'core',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'cond-bw-e-8b',
    name: 'Forearm Side Plank',
    libraryName: 'Forearm Side Plank',
    pattern: 'core',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'sq-acc-bw-17',
    name: 'Deadbug',
    libraryName: 'Deadbug',
    pattern: 'core',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'dl-acc-bw-10',
    name: 'Banded Pallof Press',
    libraryName: 'Banded Pallof Press',
    pattern: 'core',
    level: 1,
    kit: [['band']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'dl-acc-bw-12',
    name: 'Bird Dog',
    libraryName: 'Bird Dog',
    pattern: 'core',
    level: 1,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'sq-acc-db-14',
    name: 'Dumbbell Suitcase Carry',
    libraryName: 'Dumbbell Suitcase Carry',
    pattern: 'core',
    level: 1,
    kit: [['dumbbell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-kettlebell-suitcase-carry',
    name: 'Kettlebell Suitcase Carry',
    libraryName: 'Kettlebell Suitcase Carry',
    pattern: 'core',
    level: 1,
    kit: [['kettlebell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'dl-acc-db-9',
    name: 'Dumbbell Farmers Carry',
    libraryName: 'Dumbbell Farmers Carry',
    pattern: 'core',
    level: 2,
    kit: [['dumbbell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-kettlebell-farmers-carry',
    name: 'Kettlebell Farmers Carry',
    libraryName: 'Kettlebell Farmers Carry',
    pattern: 'core',
    level: 2,
    kit: [['kettlebell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-cable-pallof-hold',
    name: 'Cable Pallof Hold',
    libraryName: 'Cable Pallof Hold',
    pattern: 'core',
    level: 2,
    kit: [['cable']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'wub-fg-pallof',
    name: 'Cable Pallof Press',
    libraryName: 'Cable Pallof Press',
    pattern: 'core',
    level: 2,
    kit: [['cable']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'cond-bw-e-4b',
    name: 'Plank Taps',
    libraryName: 'Plank Taps',
    pattern: 'core',
    level: 2,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-dumbbell-suitcase-hold',
    name: 'Dumbbell Suitcase Hold',
    libraryName: 'Dumbbell Suitcase Hold',
    pattern: 'core',
    level: 2,
    kit: [['dumbbell']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-kettlebell-halos',
    name: 'Kettlebell Halos',
    libraryName: 'Kettlebell Halos',
    pattern: 'core',
    level: 2,
    kit: [['kettlebell']],
    role: 'accessory',
    movementPattern: 'rotation',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-kneeling-cable-rotations',
    name: 'Kneeling Cable Rotations',
    libraryName: 'Kneeling Cable Rotations',
    pattern: 'core',
    level: 2,
    kit: [['cable']],
    role: 'accessory',
    movementPattern: 'rotation',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'dl-acc-fg-3',
    name: 'Trapbar Farmers Carry',
    libraryName: 'Trapbar Farmers Carry',
    pattern: 'core',
    level: 3,
    kit: [['trapbar'], ['plates']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'cond-db-e-8b',
    name: 'Waiter Carry',
    libraryName: 'Waiter Carry',
    pattern: 'core',
    level: 3,
    kit: [['dumbbell', 'kettlebell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-superman-plank',
    name: 'Superman Plank',
    libraryName: 'Superman Plank',
    pattern: 'core',
    level: 3,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-side-plank-reach-throughs',
    name: 'Side Plank Reach Throughs',
    libraryName: 'Side Plank Reach Throughs',
    pattern: 'core',
    level: 3,
    kit: [],
    role: 'accessory',
    movementPattern: 'rotation',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'cond-fg-e-3b',
    name: 'Cable Woodchops',
    libraryName: 'Cable Woodchops',
    pattern: 'core',
    level: 3,
    kit: [['cable']],
    role: 'accessory',
    movementPattern: 'rotation',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-cable-reverse-woodchops',
    name: 'Cable Reverse Woodchops',
    libraryName: 'Cable Reverse Woodchops',
    pattern: 'core',
    level: 3,
    kit: [['cable']],
    role: 'accessory',
    movementPattern: 'rotation',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-banded-deadbugs',
    name: 'Banded Deadbugs',
    libraryName: 'Banded Deadbugs',
    pattern: 'core',
    level: 3,
    kit: [['band']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-side-plank-with-abduction',
    name: 'Side Plank with Abduction',
    libraryName: 'Side Plank with Abduction',
    pattern: 'core',
    level: 4,
    kit: [],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'sq-acc-fg-13',
    name: 'Ab Wheel Rollout (Kneeling)',
    libraryName: 'Ab Wheel Rollout (Kneeling)',
    pattern: 'core',
    level: 4,
    kit: [['abwheel']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-hanging-knee-raises',
    name: 'Hanging Knee Raises',
    libraryName: 'Hanging Knee Raises',
    pattern: 'core',
    level: 4,
    kit: [['pullupbar']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-kettlebell-marches',
    name: 'Kettlebell Marches',
    libraryName: 'Kettlebell Marches',
    pattern: 'core',
    level: 4,
    kit: [['kettlebell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-barbell-suitcase-hold',
    name: 'Barbell Suitcase Hold',
    libraryName: 'Barbell Suitcase Hold',
    pattern: 'core',
    level: 4,
    kit: [['barbell'], ['plates']],
    role: 'accessory',
    movementPattern: 'isometric',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-landmine-rotations',
    name: 'Landmine Rotations',
    libraryName: 'Landmine Rotations',
    pattern: 'core',
    level: 4,
    kit: [['barbell'], ['landmine', 'corner'], ['plates']],
    role: 'accessory',
    movementPattern: 'rotation',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
  {
    id: 'lib-core-earthquake-carry',
    name: 'Earthquake Carry',
    libraryName: 'Earthquake Carry',
    pattern: 'core',
    level: 4,
    kit: [['band'], ['kettlebell']],
    role: 'accessory',
    movementPattern: 'carry',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'accessory',
  },
];

/**
 * The nine conditioning exercises, from the doc's Conditioning section.
 *
 * Kept apart from LIBRARY_EXERCISES because they have no movement pattern and
 * no level: they fill the pulse raiser, the finisher and the Conditioning
 * session, and every one of them is offered at every level (with the one
 * exception in decision 7, which Phase 22 applies: beginners are not given
 * skipping in warm-ups or finishers).
 */
export const CONDITIONING_EXERCISES: readonly ConditioningExercise[] = [
  {
    id: 'lib-cond-sled-push',
    name: 'Sled Push',
    libraryName: 'Sled Push',
    kit: [['sled']],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-sled-pull',
    name: 'Sled Pull',
    libraryName: 'Sled Pull',
    kit: [['sled']],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-sled-rows',
    name: 'Sled Rows',
    libraryName: 'Sled Rows',
    kit: [['sled']],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-assault-bike',
    name: 'Assault Bike',
    libraryName: 'Assault Bike',
    kit: [['assaultbike']],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-incline-treadmill-walk',
    name: 'Incline Treadmill Walk',
    libraryName: 'Incline Treadmill Walk',
    kit: [['treadmill']],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-rowing-machine',
    name: 'Rowing Machine',
    libraryName: 'Rowing Machine',
    kit: [['rower']],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'fullgym',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-duck-walks',
    name: 'Duck Walks',
    libraryName: 'Duck Walks',
    kit: [],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-skipping',
    name: 'Skipping',
    libraryName: 'Skipping',
    kit: [],
    optionalKit: ['rope'],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
  {
    id: 'lib-cond-bear-crawl',
    name: 'Bear Crawl',
    libraryName: 'Bear Crawl',
    kit: [],
    role: 'conditioning',
    movementPattern: 'conditioning',
    equipmentRequired: 'bodyweight',
    ...PLACEHOLDER_CONTENT(),
    category: 'cardio',
  },
];
